# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tensor_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'tensor_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14tensor_service.proto\x12\tinfemeral\"\xba\x01\n\x10InferenceRequest\x12\x19\n\x11\x63loaked_embedding\x18\x01 \x01(\x0c\x12\x1d\n\x15\x65ncrypted_session_key\x18\x02 \x01(\x0c\x12\r\n\x05nonce\x18\x03 \x01(\x0c\x12\r\n\x05shape\x18\x04 \x03(\x03\x12\r\n\x05\x64type\x18\x05 \x01(\t\x12\x12\n\nsession_id\x18\x06 \x01(\t\x12\x16\n\x0emax_new_tokens\x18\x07 \x01(\x05\x12\x13\n\x0btemperature\x18\x08 \x01(\x02\"j\n\x11InferenceResponse\x12\x0e\n\x06output\x18\x01 \x01(\x0c\x12\r\n\x05shape\x18\x02 \x03(\x03\x12\r\n\x05\x64type\x18\x03 \x01(\t\x12\x18\n\x10tokens_processed\x18\x04 \x01(\x05\x12\r\n\x05\x65rror\x18\x05 \x01(\t2U\n\x0fTensorInference\x12\x42\n\x05Infer\x12\x1b.infemeral.InferenceRequest\x1a\x1c.infemeral.InferenceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tensor_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INFERENCEREQUEST']._serialized_start=36
  _globals['_INFERENCEREQUEST']._serialized_end=222
  _globals['_INFERENCERESPONSE']._serialized_start=224
  _globals['_INFERENCERESPONSE']._serialized_end=330
  _globals['_TENSORINFERENCE']._serialized_start=332
  _globals['_TENSORINFERENCE']._serialized_end=417
# @@protoc_insertion_point(module_scope)
